### PR TITLE
Making source selection translatable.

### PR DESCRIPTION
**Pull request by mbehrle**
Note: This patch needs the parallel update of all modules using get_source.

I will try to provide those patches and report here when ready.

### CODE REVIEW

**Comment by mbehrle** [comment]
Relevant references to get_source appear in:

nereid-cart-b2c/channel.py:23:    def get_source(cls):

trytond-amazon-mws/channel.py:60:    def get_source(cls):

trytond-pos/sale.py:59:    def get_source(cls):

trytond-prestashop/channel.py:86:    def get_source(cls):

trytond-magento/channel.py:148:    def get_source(cls):

trytond-ebay/channel.py:64:    def get_source(cls):

**Comment by mbehrle** [comment]
Before doing further work could you please indicate, if you will merge this request(s)? Still to do then:
trytond-amazon-mws/channel.py:60: def get_source(cls):

trytond-pos/sale.py:59: def get_source(cls):

trytond-prestashop/channel.py:86: def get_source(cls):

trytond-magento/channel.py:148: def get_source(cls):

trytond-ebay/channel.py:64: def get_source(cls):

**Comment by tarunbhardwaj** [comment]
LGTM

This can be merged, when other channels also adapt this logic.

**Comment by mbehrle** [comment]
* Tarun Bhardwaj: " Re: [trytond-sale-channel] Making source selection
  translatable. (#63)" (Wed, 02 Dec 2015 15:08:39 -0800):

> LGTM
> 
> This can be merged, when other channels also adapt this logic.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/fulfilio/trytond-sale-channel/pull/63#issuecomment-161462575

Will proceed to fix the other channels when I find a little spare time.

-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Pull request closed without merging**
